version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    template = "{{.Icon}} "
    foreground = "p:os"

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = "{{ .UserName }}@{{ .HostName }} "
    foreground = "p:blue"

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = "{{ .Path }} "
    foreground = 'p:pink'

    [blocks.segments.properties]
    home_icon = "~"
    folder_icon = "..\ue5fe.."
    style = "agnoster_short"

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = "{{ .HEAD }} "

    [blocks.segments.properties]
    branch_icon = "\ue725 "
    cherry_pick_icon = "\ue29b "
    commit_icon = "\uf417 "
    fetch_status = false
    fetch_upstream_icon = false
    merge_icon = "\ue727 "
    no_commits_icon = "\uf0c3 "
    rebase_icon = "\ue728 "
    revert_icon = "\uf0e2 "
    tag_icon = "\uf412 "

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = "\uf105"
    foreground = "p:closer"

[palette]
  os = "#ACB0BE"
  closer = "p:os"
  pink = "#F5C2E7"
  lavender = "#B4BEFE"
  blue = "#89B4FA"
