console_title_template = '{{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#45475A'
  blue = '#89b4fa'
  cyan = '#94E2D5'
  green = '#A6E3A1'
  magenta = '#F5C2E7'
  orange = '#fab387'
  purple = '#cba6f7'
  red = '#F38BA8'
  white = '#BAC2DE'
  yellow = '#F9E2AF'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = '~'
      style = 'full'

  [[blocks.segments]]
    template = '{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}'
    foreground = 'p:green'
    background = 'tranparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_ahead_icon = '⇡'
      branch_behind_icon = '⇣'
      branch_icon = ''
      branch_identical_icon = ''
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = '{{if gt .StashCount 0}} *{{ .StashCount }}{{end}}'
    foreground = 'p:yellow'
    background = 'tranparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = '{{ $staged := (add .Staging.Added .Staging.Deleted .Staging.Modified) }}{{if gt $staged 0}} +{{ $staged }}{{end}}'
    foreground = 'p:yellow'
    background = 'tranparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = '{{if gt .Working.Modified 0}} !{{ .Working.Modified }}{{end}}'
    foreground = 'p:yellow'
    background = 'tranparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

  [[blocks.segments]]
    template = '{{if gt .Working.Untracked 0}} ?{{ .Working.Untracked }}{{end}}'
    foreground = 'p:blue'
    background = 'tranparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:red{{end}}', '{{if eq .Code 0}}p:green{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
