version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = "{{ .Path }} "
    foreground = 'p:blue'
    background = "transparent"

    [blocks.segments.properties]
    style = "full"
    home_icon = "~"

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  foreground = "p:green"
  background = "tranparent"
  background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
    "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
    "{{ if gt .Behind 0 }}#B388FB{{ end }}"
  ]
  template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

    [block.segments.properties]
    fetch_status = true
    fetch_upstream_icon = true
    source = "cli"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    # change color depending on last command status
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[palette]
  black = "#45475A"   # surface1
  blue = "#89b4fa"    # blue
  cyan = "#94E2D5"    # teal
  green = "#A6E3A1"   # green
  magenta = "#F5C2E7" # pink
  orange = "#fab387"  # peach
  purple = "#cba6f7"  # mauve
  red = "#F38BA8"     # red
  white = "#BAC2DE"   # subtext1
  yellow = "#F9E2AF"  # yellow
