version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = "{{ .Path }} "
    foreground = 'p:blue'
    background = "transparent"

    [blocks.segments.properties]
    style = "full"
    home_icon = "~"

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  foreground = "p:lavender"
  background = "transparent"
  template = "{{ .HEAD }}"

  [block.segments.properties]
  fetch_status = true
  fetch_upstream_icon = true
  source = "cli"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    # change color depending on last command status
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[palette]
  blue = "#89B4FA"
  pink = "#F5C2E7"
  lavender = "#B4BEFE"
