version = 2
final_space = true
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = "{{ .Path }} "
    foreground = 'p:blue'
    background = "transparent"

    [blocks.segments.properties]
      style = "full"
      home_icon = "~"

# git segment should look like
# master(green) ⇣42⇡42 *42(green) merge(depends) ~42(red) +42(yellow) !42(yellow) ?42(blue)
  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:green"
    background = "tranparent"
    template = "{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}"

    [blocks.segments.properties]
      branch_icon = ""
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:blue"
    background = "tranparent"
    template = """ {{ if .Working.Changed }} {{ .Working.String }}{{ end }}"""

    [blocks.segments.properties]
      branch_icon = ""
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

  [[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:red"
    background = "tranparent"
    template = """ {{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}"""

    [blocks.segments.properties]
      branch_icon = ""
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    # change color depending on last command status
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[palette]
  black = "#45475A"   # surface1
  blue = "#89b4fa"    # blue
  cyan = "#94E2D5"    # teal
  green = "#A6E3A1"   # green
  magenta = "#F5C2E7" # pink
  orange = "#fab387"  # peach
  purple = "#cba6f7"  # mauve
  red = "#F38BA8"     # red
  white = "#BAC2DE"   # subtext1
  yellow = "#F9E2AF"  # yellow
